database:
  type: sqlite
  mysql:
    address: 178.255.219.105:3306
    username: u2275_KeBL2QKEWr
    password: mnjQHGFFKq.LsUBbqe@HNnF!
    database: s2275_factions
  sqlite:
    file: vips.sql

Rewards:
  feather:
    comandos:
      - 'darbau {player}'
      - 'darbau {player}'
      - 'darbau {player}'

  mvp:
    comandos:
      - 'darbau {player}'
      - 'darbau {player}'

  pro:
    comandos:
      - 'darbau {player}'